refactor: Renamed script to what-the-preview

diff --git a/what-the-preview b/what-the-preview
--- a/what-the-preview
+++ b/what-the-preview
@@ -2,6 +2,14 @@
 input_video=$1
 previews_amount=$2
 
+if [ -z "$1" ] || [ -z "$2" ]; then
+    echo "Missing arguments"
+    echo ""
+    echo "Usage:"
+    echo "what-the-preview <name_of_the_video> <previews_amount>"
+    exit 1
+fi
+
 # Get the filename without path and without fileextension
 filename=$(basename -- "$input_video")
 filename="${filename%.*}"
